require:
  - rubocop-performance
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'sig/**/*'
    - 'vendor/**/*'
  SuggestExtensions: false
RSpec/ExampleLength:
  Max: 10
