name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: check development
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.0'
          - '3.1.0'
          - '3.2.0'
          - head
          - jruby-head

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: test development
    name: rubocop
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1
        bundler-cache: true
    - name: Lint the code
      run: bundle exec rubocop --parallel
  reek:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: test development
    name: reek
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1
        bundler-cache: true
    - name: Check for code smells
      run: bundle exec reek
  steep:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: test development
    name: steep
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1
        bundler-cache: true
    - name: Static type check
      run: bundle exec steep check
